### PR TITLE
feat: Rewrite theme

### LINKED ISSUE #4: Side bar scrolls left and off the page when selecting nested pages
With the Introduction page selected, the side bar looks good:

but when I select the Introduction page, the side bar shifts to the left and is partially cut off:

The side bar also scrolls left and right a bit, so I'm betting there's a width that just has to be massaged a little.

### PR DESCRIPTION
**Pull request by jacobgkau**
We've started experiencing multiple issues with the current default theme, including:

- For some reason, bullet points and numbers for unordered and ordered lists were hidden, and circles were being rendered to simulate bullets in unordered lists (but ordered lists were broken).
- The sidebar had bad padding and scrollbars (see https://github.com/pop-os/docs/issues/4).
- The top bar was sticky, but also transparent, so it looked bad when the page was scrolled.

Digging into the current theme, it seemed very complicated (possibly like it was copied from the support docs website?) This rewrite started with mdbook's default theme, and changed only what was necessary to apply the Pop colors and Pop/System76 fonts. I pulled the colors from the [Pop GTK theme](https://github.com/pop-os/gtk-theme/blob/master/gtk/src/light/gtk-3.0/_colors-pop.scss)'s light and dark colors.

Fixes #4.
Obsoletes #3.

### CODE REVIEW

**Comment by jacobgkau** [comment]
We may run into more that needs to be tweaked in the future, but for now, this covers everything currently being used. I added a placeholder table on the empty introduction page to show what those look like.

@Ampersandstorm Take note that we'll want to indent any pictures, block quotes, etc. with four spaces if they're part of a list item. Otherwise, they show up wider than the text, which looks awkward.

**Review by Ampersandstorm — CHANGES_REQUESTED** [review]
This looks great! One minor thing I did notice is the rounded edges in screenshots present in the old theme. Is it possible to get this back, or to automatically apply some kind of border or other effects? I feel like the sharp-edged images appear "pasted" into place.
image

**Comment by jacobgkau** [comment]
Great catch, I hadn't even noticed they were rounded before. Fixed with https://github.com/pop-os/docs/pull/5/commits/d3331697f17b4aba371ac707182aaf1adb0d46da.

**Review by Ampersandstorm — APPROVED** [review]

**Review by gangwerz — APPROVED** [review]
Changes look good!
Like the theme, especially that font list

**Pull request merged**
